#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source & header files in this project (main.cpp is automatically assumed)

HEADERS += note.hpp
HEADERS += melody.hpp
HEADERS += note_player.hpp
HEADERS += fur_elise.hpp
# HEADERS += note_printer.hpp
HEADERS += song.hpp

HEADERS += note_player_gpio.hpp
SOURCES += note_player_gpio.cpp

# HEADERS += rtttl_player.hpp
# SOURCES += rtttl_player.cpp

# other places to look for files for this project
SEARCH  := 

# set REATIVE to the next higher directory 
# and defer to the Makefile.due there
RELATIVE := $(RELATIVE)../
include $(RELATIVE)Makefile.due



song.hpp : generator
	./generator

generator : generator.o rtttl_player.o
	g++ -std=c++17 generator.o rtttl_player.o -o generator

generator.o : generator.cpp rtttl_player.hpp note_printer.hpp
	g++ -std=c++17 -c generator.cpp -o generator.o

rtttl_player.o : rtttl_player.cpp rtttl_player.hpp
	g++ -std=c++17 -c rtttl_player.cpp -o rtttl_player.o

